### ISSUE TITLE
[2] Création des notifications par email

### ISSUE THREAD

**Issue by MaxLf** [eleven-labs/coach-bot#1]
Le **23 du mois M-1** chaque **coach Technique** et **RH** doit recevoir un email contenant tous les points de suivis et les bilans OKR qu'il doit effectuer **pendant le mois M.**

Ce mail doit contenir à minima : 
- La **liste des bilans**
- La **liste des points de suivis**
- Pour chacun le **nom + prénom du coaché** (**Colonnes A et B** du Google Sheet)
- Pour chacun le Prénom du **coach** (**colonne D** du Google Sheet)
- Pour chacun le Prénom du **RH** (**colonne G** du Google Sheet)

Les **mails des coachs** sont à la **colonne F** du Google Sheet et les **mails des RH** en **colonne I**).

Pour chaque mail, **Maxime doit être en CC** pour avoir également un bilan du mois à venir.

Ex de mail : 
" Salut [Prénom du coach]

Voici ton planning de coaching du mois à venir :)

Bilans à effectuer : 
- Astronaute X avec [Prénom du coach] et [Prénom du RH]
- Astronaute Y avec [Prénom du coach] et [Prénom du RH]
...

Point de suivis à effectuer : 
- Astronaute Z avec [Prénom du coach] et [Prénom du RH]
...

Je te conseil d'aller voir dès maintenant avec eux pour prévoir quand faire tout ça !

A bientôt,
Wilson."

**Comment by eko** [comment]
Hello,

L'envoi de mail (via Mandrill) a été implémenté :)
