### ISSUE TITLE
[1] Création d'une conversation Slack entre le coaché, le coach et le RH

### ISSUE THREAD

**Issue by MaxLf** [eleven-labs/coach-bot#2]
Le **23 du mois M-1** le bot doit démarrer une **conversation à 3** avec le **coaché + coach technique + RH** pour leur indiquer qu'ils ont un **point de suivi ou un bilan OKR** à effectuer **lors du mois M**.

Ce Slack peut être de la forme : 

" Salut tous les 3,

À partir de la semaine prochaine, vous devez vous retrouver pour planifier le [point de suivi / bilan OKR] de [nom du coaché].

Je vous laisse le soin de trouver une date à laquelle vous êtes tous les 3 disponibles.

A bientôt,
Wilson."

Pour info : 
- **Prénom du coaché** = **Colonne B** du Google Sheet
- **Slack du coaché** = **Colonne C** du Google Sheet
- **Slack du coach** = **Colonne E** du Google Sheet
- **Slack du RH** = **Colonne H** du Google Sheet

**Comment by eko** [comment]
Hello,

Le format de la Google Spreadsheet a été mis à jour dans le code du bot et la discussion Slack sera maintenant lancée avec les trois intervenants.
